site_name: App Receitas

repo_name: fga-eps-mds/2025.1-AppReceitas-Docs
repo_url: https://github.com/fga-eps-mds/2025.1-AppReceitas-Docs

theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.top
  
nav: 
  - Início: index.md
  - Artefatos:
    - Lean Inception: artefatos/leaninception.md
  - Planejamento: 
    - Comunicação: planejamento/comunicacao.md
    - Conhecimento: planejamento/conhecimento.md
    - Custos: planejamento/custos.md
    - Riscos: planejamento/riscos.md
    - Tempo: planejamento/tempo.md
  - Sprints:
    - Atas Reuniões: 
      - Reunião 1 (Lean Inception): sprints/atas_reunioes/ata1.md
    - Sprint 1: sprints/sprint_1.md
  - Políticas: 
    - Politica de commmits: politicas/politica_commits.md
